# Generated by Django 2.0.6 on 2018-07-07 05:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Linea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('gramos', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Metro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('linea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infsoc.Linea')),
            ],
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.IntegerField(blank=True)),
                ('comuna', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='infsoc.Comuna')),
                ('cuenta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('metro', models.ManyToManyField(to='infsoc.Metro')),
            ],
        ),
        migrations.AddField(
            model_name='transaccion',
            name='comprador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comprador', to='infsoc.Usuario'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='comunas',
            field=models.ManyToManyField(to='infsoc.Comuna'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='lineas',
            field=models.ManyToManyField(to='infsoc.Linea'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='medicamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infsoc.Medicamento'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='vendedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendedor', to='infsoc.Usuario'),
        ),
    ]
