# Generated by Django 2.0.6 on 2018-07-07 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infsoc', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='linea',
            options={'ordering': ['numero']},
        ),
        migrations.AddField(
            model_name='linea',
            name='numero',
            field=models.IntegerField(default=1, unique=False),
            preserve_default=False,
        ),
    ]
