# Generated by Django 2.0.6 on 2018-07-07 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infsoc', '0005_metro_comuna'),
    ]

    operations = [
        migrations.AddField(
            model_name='metro',
            name='numero',
            field=models.IntegerField(default=1),
        ),
    ]
