# Generated by Django 2.0.6 on 2018-07-07 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infsoc', '0006_metro_numero'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metro',
            options={'ordering': ['numero']},
        ),
        migrations.RenameField(
            model_name='medicamento',
            old_name='gramos',
            new_name='miligramos',
        ),
    ]
