# Generated by Django 2.0.6 on 2018-07-08 19:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infsoc', '0009_auto_20180708_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
