# Generated by Django 2.0.6 on 2018-07-08 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infsoc', '0015_auto_20180708_2010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='comuna',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='cuenta',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='metro',
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='comprador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comprador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='comunas',
            field=models.ManyToManyField(blank=True, null=True, to='infsoc.Comuna'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='vendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendedor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
