# Generated by Django 2.0.6 on 2018-07-08 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infsoc', '0016_auto_20180708_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='estado',
            field=models.CharField(choices=[('PUESTO', 'PUESTO'), ('CONTACTADO', 'CONTACTADO'), ('LISTO', 'LISTO')], default='PUESTO', max_length=255),
        ),
    ]
